AWSTemplateFormatVersion: 2010-09-09
Description: Creates a VPC with public and private subnets 
Resources:
  VPC: 
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 192.168.101.0/24
  PublicSubnetA: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: "eu-west-2a" 
      CidrBlock: 192.168.101.0/28
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
  PrivateSubnetB: 
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: "eu-west-2b"
      CidrBlock: 192.168.101.32/28
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
